List<(String, String)> noteDatabase = [
  ('Grocery List', 'Milk, Eggs, Bread, Butter'),
  ('Meeting Notes', 'Discuss Q2 goals and OKRs'),
  ('Workout Plan', 'Monday: Chest, Tuesday: Back'),
  ('Flutter Tips', 'Use const widgets for performance'),
  ('Book Ideas', 'Story about a time-traveling cat'),
  ('To-Do Today', 'Fix bug, Email team, Update README'),
  ('Quotes', '“Stay hungry, stay foolish.”'),
  ('Birthday Reminder', 'Mom - April 5th'),
  ('Travel Plans', 'Osaka itinerary: Dotonbori, USJ'),
  ('Project Roadmap', 'Phase 1: Research, Phase 2: MVP'),
  ('Learning Goals', 'Learn German, Deepen AI skills'),
  ('Shopping Wishlist', 'iPad, Mechanical Keyboard'),
  ('Favorite Recipes', 'Carbonara, Teriyaki Chicken'),
  ('Budget Tracker', 'March: Food \$250, Transport \$80'),
  ('Conference Notes', 'Keynote by John, amazing UX demo'),
  ('Design Checklist', 'Contrast ratio, Padding, Icons'),
  ('App Ideas', 'Habit tracker with gamification'),
  ('Daily Journal', 'Today I learned about tuples in Dart'),
  ('Movie List', 'Interstellar, The Matrix, Dune'),
  ('Gift Ideas', 'Personalized mug, Bluetooth speaker'),
];
